### ISSUE TITLE
A2plus support

### ISSUE THREAD

**Issue by johndoe2323** [dprojects/getDimensions#11]
Darek - my workflow now consists of assembling ready-made furniture pieces together into a larger build.
For example, for different cabinet types I have several template FreeCAD files which are fully parameterized, e.g. for shelves, cabinets, cabinat doors etc.. When building a larger project I then compile the build by composing various template files in A2plus.
Do you have any plans supporting external parts?
Thanks!

**Comment by dprojects** [comment]
Personally, I don't use A2plus and Assembly. There are two reasons for that:

1. I never had time to learn it, this is difficult to use. Also I saw A2plus creates special objects that might not be supported by all FreeCAD operations. 
2. I am more into not-bound modeling. If you have bounded objects like for example Pad on Pad at PartDesign you can't move them, create gap between them or replace. This is significant issue. Not-bounded modeling gives more freedom, especially in case of redesign. You can remove or replace any object, even nested very deeply. You can switch visibility of any object. 

However, I don't say no for A2plus or Assembly support, I even don't know if this is the same thing. I should look at this more closely. But I need sample simple file with such objects that should be supported. 

You can provide file sample? I need A2plus installed? or something else? But not huge. Just simple 2 Cubes created with A2plus or whatever it is called. Maybe simple operation on that you use often. I will look at it and tell you if this is possible to calculate such objects.

**Comment by johndoe2323** [comment]
Please see attached - one file containing a simple cabinet.
Another containing an assembly of two aforementioned cabinets. The generated getDimension report shows nothing.

[Simple Cabinet Assembly.zip](https://github.com/dprojects/getDimensions/files/10316428/Simple.Cabinet.Assembly.zip)

**Comment by johndoe2323** [comment]
(you need A2plus installed from AddonManager)

**Comment by johndoe2323** [comment]
I think I found a great workaround - using Assembly4!!!
Your script works  just fine there - see example.
(Assembly4 required from AddonManager)

[Simple Assembly 4.zip](https://github.com/dprojects/getDimensions/files/10316462/Simple.Assembly.4.zip)

**Comment by dprojects** [comment]
I will try to look at A2plus and Assembly more closely, maybe this week. 
Let me keep this issue open to remember about it.

**Comment by dprojects** [comment]
- The "Simple Cabinet" is fine, just supported FreeCAD objects.
- The "Simple Assembly" not shows anything because there are 2 objects inside. The objects are some kind of bricks ;-) there are no information about parts. There is only link to  source file. However, I need to see if it is possible to follow those files if I have installed A2plus. 
- The last file "Simple Assembly 4" is fine because there are parts, not 2 bricks ;-) As far the parts are supported by getDimensions this will be fine. However, there are App::Links to another document. Normally, getDimensions works only at ActiveDocument not across many documents. But looks like the Links are made in such a smart way that the tool is able to follow the Links from ActiveDocument to other not-active document. What is surprising and very nice. 

So looks like Assembly 4 ? it is called like this ? is supported but the A2plus is not supported... but I will look into that.

**Comment by johndoe2323** [comment]
Nah just forget A2plus - it does not even support linked objects (Std_MakeLink) so unusable as such...

**Comment by dprojects** [comment]
> Nah just forget A2plus - it does not even support linked objects (Std_MakeLink) so unusable as such...

Many people use Assembly and A2plus so maybe there is field to improve better integration with those extensions. For example I am thinking to make single button click to create Links and LCS for each Part or LinkGroup. I don't know if there is such thing or not at Assembly 4? For example if you create model you could click single button, some kind of "export to Assembly" and this would create all needed LCS and Links for your model. 

I will look at A2plus and Assembly 4, but first need to learn a little bit more about it, how to use it.
