### ISSUE TITLE
Dimensions in fractions of a millimeter

### ISSUE THREAD

**Issue by wsad4ryba** [dprojects/getDimensions#17]
Is there an option to display dimensions in millimeters in the list with at least one decimal place, not rounded?

**Comment by dprojects** [comment]
Why you need such precision? I guess woodworkers are not able to achieve precision below 2 mm, even CNC in wood might not be so precise? 

The right place to change it probably will be `getUnit` function but I am not sure if I will be able to find place for new option at the menu screen. So you need to provide good argument for this change :-)

**Comment by wsad4ryba** [comment]
I'll explain. Right now I'm designing a built-in wardrobe. If I want to fit it perfectly with four columns of shelves (I use expressions to calculate dimensions), then rounding off by 0.5mm will ultimately give me a 2mm shift. If it's rounding up, the last shelf simply won't fit.
![obraz](https://github.com/user-attachments/assets/29703f71-3c51-4aca-9310-c27d7faf38ad)


As for cutting accuracy, achieving 0.5mm shouldn't be a problem. It seems to me that most suppliers of furniture boards can achieve such accuracy, my favorite offers an accuracy of 0.3mm (meble.pl).

If such accuracy were not achievable, it would be even more useful if the summary showed a more accurate dimension, because you could consciously decide to change the size.

In the case of free-standing furniture, it's easier because such rounding off shouldn't cause a problem, unfortunately in the case of built-in furniture, it would be best to adjust even to a quarter of a millimeter ;)
I hope this convinced you :)

**Comment by wsad4ryba** [comment]
I'll explain. Right now I'm designing a built-in wardrobe. If I want to fit it perfectly with four columns of shelves (I use expressions to calculate dimensions), then rounding off by 0.5mm will ultimately give me a 2mm shift. If it's rounding up, the last shelf simply won't fit.
<img width="287" alt="example" src="https://github.com/user-attachments/assets/e1970790-47bf-4789-998d-9e70ba9f98b8">


As for cutting accuracy, achieving 0.5mm shouldn't be a problem. It seems to me that most suppliers of furniture boards can achieve such accuracy, my favorite offers an accuracy of 0.3mm (meble.pl).

If such accuracy were not achievable, it would be even more useful if the summary showed a more accurate dimension, because you could consciously decide to change the size.

In the case of free-standing furniture, it's easier because such rounding off shouldn't cause a problem, unfortunately in the case of built-in furniture, it would be best to adjust even to a quarter of a millimeter ;)
I hope this convinced you :)

**Comment by dprojects** [comment]
> As for cutting accuracy, achieving 0.5mm shouldn't be a problem. It seems to me that most suppliers of furniture boards can achieve such accuracy, my favorite offers an accuracy of 0.3mm (meble.pl).

Siema ziomek z Polski :-) I usually order chipboards at Castorama and they usually cut everything perfectly, I am pretty sure it is much below 1 mm.  

> I use expressions to calculate dimensions), then rounding off by 0.5mm will ultimately give me a 2mm shift. If it's rounding up, the last shelf simply won't fit.

I am not sure if this work like this, if you are using expressions this might be a problem with calculation. 
Maybe you could provide FreeCAD file with such simple example, so I will be able to check what is going on there. 

> I hope this convinced you :)

Probably not :-) because I am not sure if it is not problem with expressions calculation.
You can quickly try change [the 0 value into 2 at getUnit function](https://github.com/dprojects/getDimensions/blob/8d9f296bbf6a06a75192d28ecca9fd3c98239894/getDimensions.py#L824) and see if this will be solved or send me FreeCAD file example. 

btw: I saw there is FreeCAD 1.0 released so I have to add support for this new release, there are some not working things (like Sketch creation and colors and maybe something other).

**Comment by wsad4ryba** [comment]
Siemanko :)
When it comes to calculations, the result in the object data seems correct, but the same object on the cutting list is already rounded.
<img width="244" alt="object_data_before" src="https://github.com/user-attachments/assets/f71d5ec5-8217-40cf-9d16-01bf08a98ccb">
<img width="661" alt="cut_list_before" src="https://github.com/user-attachments/assets/414bb9b7-c34e-4d4f-ac0d-eaee3d1b9a12">

I made the change you mentioned (of course I also removed the int cast) and now the result is the same in both places:
<img width="250" alt="object_data_after" src="https://github.com/user-attachments/assets/428ff7ec-66c0-4d01-83f7-6b0bf9f443e3">
<img width="657" alt="cut_list_after" src="https://github.com/user-attachments/assets/61b43b38-4693-480d-a714-b4544134d6e9">

This is my wardrobe project and my first one in Woodworking workbench, so I would be grateful for a review ;) As I wrote earlier, it's a built-in wardrobe, so I use the dimensions of the available space as a basis for calculations.
[Szafa_Sypialnia_v2_backup.zip](https://github.com/user-attachments/files/17894444/Szafa_Sypialnia_v2_backup.zip)

**Comment by dprojects** [comment]
> I made the change you mentioned (of course I also removed the int cast) and now the result is the same in both places

OK, I will add new option for the precision but maybe first I will add support for FreeCAD 1.0 and probably the new option will be available in 1.0 stable. However, if you have some ideas where the new option could be added at menu screen, you can post it here meanwhile (image or something).

**Comment by wsad4ryba** [comment]
Of course, there is no rush, support for the new version is more important
As for where to place it, it should fit under the units, e.g. something like this:
![obraz](https://github.com/user-attachments/assets/aa27be4a-e26a-4c73-b0cb-a1855be38b44)

Besides, I guess this option could be used for all units, or in other words, simply everywhere where rounding is used?

**Comment by dprojects** [comment]
> Of course, there is no rush, support for the new version is more important 

The FreeCAD 1.0 has more changes than expected. I added support for Cube -> Pad conversions but I saw there is also problem with Sketch movement. So, I can't submit these support for FreeCAD 1.0 yet because it would break the master branch. So I made the precision feature first because the FreeCAD 1.0 needs testing each feature more carefully.

> As for where to place it, it should fit under the units, e.g. something like this: 
> Besides, I guess this option could be used for all units, or in other words, simply everywhere where rounding is used?

You have similar point of view to mine but I was thinking a little bit about this feature and this is more complicated. In fact you need 3 (mm, inches, meter) default values for dimensions, area and edge. So there is 9 defaults and they need to be changed together with units changes. 

So this is how I did it:

![ds001](https://github.com/user-attachments/assets/e6045402-bb45-4a49-92d2-4e3cd4a5c785)

**Make a note:** You can't get rid of integer casting because at the report you may have values like `499.9999999` in some cases and it is better to have backward compatibility. 

Docs for this feature: [here](https://github.com/dprojects/getDimensions/tree/master/Docs#precision)
Changes needed for this feature: [here](https://github.com/dprojects/getDimensions/commit/a740f562f4260b4d115bee5272fe7ca56cc4d9d7)

Let me know what do you think.

**Comment by wsad4ryba** [comment]
Sorry for the late reply.
I tested these changes and from my point of view it's great :)
By default everything is the same, but if someone wants to play with fractions they have such an option.

**Comment by dprojects** [comment]
> if someone wants to play with fractions they have such an option.

Yes, this is the idea to give someone choice and keep the correct defaults if someone is not so familiar with details.
